1D array

In [48]:
import numpy as np
#import numpy
#from numpy import random

In [46]:
#using list
marksheet=[45,46,38,49,416]
type(marksheet)

TypeError: 'list' object is not callable

In [39]:
a1=np.array(marksheet)
a1

array([45, 46, 38, 49, 41])

In [40]:
type(a1)

TypeError: 'list' object is not callable

In [41]:
a2=np.array(marksheet,dtype=float)
a2

array([45., 46., 38., 49., 41.])

In [42]:
a2=np.array(marksheet,dtype=str)
a2

array(['45', '46', '38', '49', '41'], dtype='<U2')

In [44]:
4500+4000+5400

13900

In [71]:
a2=np.array(marksheet,dtype=str)
a2

array(['45', '46', '38', '49', '416'], dtype='<U3')

In [70]:
print("Dimension:",a1.ndim)
print("size",a1.size)
print("Shape",a1.shape)
print("datatype",a1.dtype)
print("datatype",a2.dtype)

Dimension: 1
size 5
Shape (5,)
datatype int32
datatype <U3


In [69]:
print("DImension",a1.dtype)
int 4 bytes
1 bytes= 8bit
00000000
4bytes*8bis=32bit
00000000000000000000000000000000

SyntaxError: invalid syntax (4102539462.py, line 2)

In [68]:
np.array([1,2,3],dtype="int8")

array([1, 2, 3], dtype=int8)

In [67]:
print("1itemSize:",a1.itemsize)

1itemSize: 4


In [66]:
print("ItemSize:",a1.item)

ItemSize: <built-in method item of numpy.ndarray object at 0x0000023251DFE570>
