In [1]:
import numpy as np

In [2]:
marks=[45,46,38,49,41]

In [3]:
np.asarray(marks)#if given object is an array it will not create a new array

array([45, 46, 38, 49, 41])

In [4]:
a1=np.array(marks)
a1

array([45, 46, 38, 49, 41])

In [5]:
np.asarray(a1)

array([45, 46, 38, 49, 41])