In [1]:
import numpy as np

In [2]:
#arange(start,end,step)
a1=np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a1=np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a1=np.arange(1,10,dtype=float)
a1

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
a1=np.arange(1,20,2)
a1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
a1=np.arange(1,20,1)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [7]:
a1=np.arange(1,20,3)
a1

array([ 1,  4,  7, 10, 13, 16, 19])

In [9]:
#linspace(strat,end,count)
lin1=np.linspace(1,10)
lin1

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
len(lin1)

50

In [11]:
lin2=np.linspace(1,10,10)
lin2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
lin3=np.linspace(1,10,10,dtype=int)
lin3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
lin4=np.linspace(1,10,20,dtype=float)
lin4

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])